php:
  build: .
  ports:
   - "8080:80"
   - "8043:443"
  volumes:
   - ./www:/var/www/html
db:
  image: mysql:5.7
  ports:
   - "3306:3306"
  volumes:
   - ./db:/var/lib/mysql
  environment:
   - MYSQL_ROOT_PASSWORD=123
   - MYSQL_DATABASE=phprs